### ISSUE TITLE
Контрольные работы 3 и 4 - совпадает одна задача

### ISSUE THREAD

**Issue by tkhirianov** [mipt-cs-on-python3/course-site#12]
Задача B в контрольной 3 совпадает с задачей A в контрольной 4.

**Comment by tkhirianov** [comment]
Нужно заменить задачу в 4-м контесте на условно-аналогичную как можно скорее. Контест уже идёт.

**Comment by tkhirianov** [comment]
Максим, сделаешь?

**Comment by mkhlamov** [comment]
Я не заливал задачи на контесты никогда, и сегодня на полдня у меня не будет доступа к компьютеру. Боюсь, что не успею разобраться. Нельзя на эту issue кого-то другого назначить, а я потом отработаю на других задачках, когда будет больше времени?

**Comment by tkhirianov** [comment]
Лариса, ты сможешь это сделать?

**Comment by tkhirianov** [comment]
На следующий год работы будут сделаны заново по новой системе.
