### ISSUE TITLE
Практика 10 - аттрибуты классов и экземпляров

### ISSUE THREAD

**Issue by Oloshka** [mipt-cs-on-python3/course-site#13]
```
>>> class MySecondClass:
        msg = 'Hello' # Все экземпляры этого класса будут иметь атрибут msg,
                # равный "Hello"
                # Но впоследствии мы его можем изменить
        def doSmth(self):
                return self.msg

>>> b = MySecondClass()
>>> b.doSmth()
'Hello'
>>> MySecondClass.doSmth(b)
'Hello'
>>> b.msg = 'Good by'
>>> b.doSmth()
'Good by'
```

В этом листинге описание немного не соответствует действительному положению дел.

`msg = 'Hello'` - атрибут уровня класса.
`b.msg = 'Good by'` - создает атрибут msg у экземпляра b

Атрибут уровня класса по-прежнему доступен и остался прежним:

```
»> MySecondClass.msg
'Hello'
```

```
>>> MySecondClass.__dict__
{'msg': 'Hello', '__weakref__': <attribute '__weakref__' of 'MySecondClass' objects>, '__module__': '__main__', '__doc__': None, '__dict__': <attribute '__dict__' of 'MySecondClass' objects>, 'doSmth': <function MySecondClass.doSmth at 0x7fe3c3d47840>}
>>> b.__dict__
{'msg': 'Good by'}
```

Путаница между двумя разными уровнями аттрибутов может быть вызвана тем, что внутри класса можно обращаться к ним обоим через self. Вначале происходит поиск в аттрибутах экземпляра (`b.__dict__`), а затем среди аттрибутов класса (`MySecondClass.__dict__`).

**Comment by fufler** [comment]
Полностью согласен. Мы этот вопрос уже обсудили, но в текст работы правки ещё не внесли. Тикет не закрываю, пусть висит как напоминание.

**Comment by tkhirianov** [comment]
Владимир, исправь это и закрой основную багу https://github.com/mipt-cs-on-python3/course-site/issues/28

**Comment by senya** [comment]
Так, этого кода больше в лабе нет. Закрываю.
