### ISSUE TITLE
lab6: Вопрос по задаче А

### ISSUE THREAD

**Issue by Snorch** [mipt-cs-on-python3/course-site#15]
В тесте 12 где на ввод подается 100к чисел, какое решение, предполагалось, должны написать студенты, чтобы не получить 'T' таймаут? Использовать set студенты еще не могут, так как он, очевидно, проходится в семинаре 10 ("Словари и множества в Python"), про бинарный поиск вроде им тоже ни чего не говорили, делать костыли и подпираться под тест - вроде не красиво. Может я что-то упустил?

**Comment by fufler** [comment]
[«Официальное» решение](https://github.com/mipt-cs-on-python3/course-site/blob/master/content/solutions/lab6/A.py). Насколько оно согласуется с лекциями, лучше уточнить у Тимофея.

**Comment by Snorch** [comment]
Тогда, наверно нужно добавить sort в "Операции со списками" http://judge.mipt.ru/mipt_cs_on_python3/labs/lab5.html#id4 Точно, могло же еще быть в лекции.

**Comment by tkhirianov** [comment]
В 2016 году работа по тестированию и непрерывной интеграции будет в середине второго семестра.
Так что проблема автоматически снимается.
