### ISSUE TITLE
Лабораторная №3 - исправление и доработка

### ISSUE THREAD

**Issue by tkhirianov** [mipt-cs-on-python3/course-site#17]
Лабораторная работа: Черепашка
Вычитать и доделать лабораторную работу: Максим Хламов
Приёмку работы делает Алексей Ермаков

**Comment by tkhirianov** [comment]
План правки такой:
redline для данной issue: 11 сентября (воскресенье)
_Максим_ коммитит draft и закрывает (close) данную issue.
После коммита версии, удовлетворяющей _Максима_, с утра понедельника по вечер вторника **все** лабники могут вычитать draft лабораторной работы и пишут замечания **сюда**.
Алексей, вычитывая работу, и исходя из серьёзности замечаний переоткрывает багу столько раз, сколько нужно.
Стараемся всё утрясти до вечера вторника.
Среда -- день тишины. Все могут прорешать финальную версию лабораторной работы, чтобы точно знать что будет завтра (т.к. у большинства эта лаба в четверг).

**Comment by mkhlamov** [comment]
Закоммитил. Основные дополнения: задача FizzBuzz и нарисовать смайлик. Остальное - мелкие исправления/дополнения

**Comment by tkhirianov** [comment]
Смайлик и паук - отличные задачи. :-) Или паук уже был до тебя?
По поводу рекурсии - думаю, её следует убрать из этой работы и перенести в заготовку работы №9.

**Comment by tkhirianov** [comment]
В следующем, 2017 году эта лаба, мне кажется, должна быть разбита на две -- одна просто циклы, без использования функций, а вторая уже с функциями.
