### ISSUE TITLE
Лабораторная №4 - исправление и доработка

### ISSUE THREAD

**Issue by tkhirianov** [mipt-cs-on-python3/course-site#18]
Переписать исполнителя Робот так, чтобы он тебе нравился.
При этом команды робота должны быть:
up()
down()
left()
right()
paint()
без упоминания объекта робота.

Набор задач тебе сбросить в каком формате? Есть редактор карт для робота на КуМир-е.
Где и в каком формате ты будешь хранить задачи и ответы?

**Comment by tkhirianov** [comment]
План правки такой:
redline для данной issue: 18 сентября (воскресенье)
Алексей коммитит draft и закрывает (close) данную issue.
с утра понедельника по вечер вторника все лабники могут вычитать draft лабораторной работы и пишут замечания сюда. Стараемся всё утрясти до вечера вторника.
Среда -- день тишины. Все могут прорешать финальную версию лабораторной работы.

**Comment by fufler** [comment]
@tkhirianov Скинь в том виде, в котором тебе удобно. В идеале — картинка с описанием. Если вдруг уже есть готовые файлы какого-то формата, то можешь прислать их.

**Comment by tkhirianov** [comment]
Редактор карт входит в программу:
https://www.niisi.ru/kumir/

Не до конца понимаю что при этом пиется в клетке Wall. Возможно, это
битовое ИЛИ из 1, 2, 4, 8, где числа отвечают стенам.

**Comment by fufler** [comment]
Было бы здорово, если б ты указал список конкретных задач, которые нам нужны. Боюсь, что редактор не особо поможет: мы хотели сделать динамически генерируемые уровни, например, когда вертикальная стена появляется на разном расстоянии от границы.

**Comment by tkhirianov** [comment]
Простые последовательности команд
1-1 1-2 1-3

Использование подпрограмм
2-1 2-2 2-4 2-5

Условное исполнение
3-1 3-2 3-3 (мышь сбегает из мышеловки)

Циклы с условием
5-2 5-3 5-1 5-4 5-6 5-7 5-8 5-9 5-11 5-12 6-2

Условные действия на каждой итерации цикла
6-1 6-4
8-1 8-2 8-4 8-3 8-5 8-6 8-7 8-9 8-10 8-11 8-13 8-14 8-17 
(для задач цикла 8 нужно клетку, в которой изначально стоит робот, исключить из "коридора", в котором осуществляется условное закрашивание, чтобы не было "костылей" с нулевой итерацией или пост-итерацией)

Циклы, вложенные в условия
8-21 8-22 8-27 8-28 8-29 

Использование переменных-флагов и переменных-счётчиков
3-4 3-9 3-10 7-0 7-3 7-4 7-5 7-6 7-7 8-18 8-19 

Вложенные циклы
4-3 4-11 4-12 4-13 4-14 4-15 4-16 5-10 5-14
6-6 6-7 6-8 8-30

Вычислительные задачи для Робота
9-2 9-3 9-6 9-7 9-8 9-9 9-10

Номера указаны по роботу Бориса Власенко.

**Comment by fufler** [comment]
Столько задач нереально сделать за две пары. Нужно сократить список до 15-20 задач.
