### ISSUE TITLE
В лабе 5 не сказано явно, что ввод через файл

### ISSUE THREAD

**Issue by RerRayne** [mipt-cs-on-python3/course-site#22]
В лабе  после задания 5 нигде явно не сказано, что входные данные подаются через файл, хотя, судя по контенту лабы, это подразумевается.

**Comment by tkhirianov** [comment]
@RerRayne, если знаешь, кто делал лабу 5, можешь сразу делать assign.
В данном случае это лучше заводить вообще не отдельной багой, а писать комментарий к баге #20

**Comment by tkhirianov** [comment]
Василий, не срочно, но нужно исправить. Не откладывай на 2017-й год.

**Comment by vasyarv** [comment]
@RerRayne а насколько я понимаю там и не требуется это. Хоть на лабе и рассказывали про файлы, но вводили с клавиатуры. Я думаю если там сделать требование про ввод с файла, то будут затруднения и не успеют сделать

**Comment by tkhirianov** [comment]
Так требуется или нет изменение в тексте лабораторной?
@RerRayne , согласишься с Васей?
