### ISSUE TITLE
Лабораторная №8 "Словари и множества в Python" - доработка

### ISSUE THREAD

**Issue by tkhirianov** [mipt-cs-on-python3/course-site#24]
**Лабораторная работа: Словари и множества в Python**

Она является [работой №10 прошлого года](http://judge.mipt.ru/mipt_cs_on_python3_2015/labs/lab10.html)

Требуется:

1. Исправить форматирование кода (особенно отступы кода в таблице про словарь).
2. Добавить простых и интересных упражнений на словари

**Comment by tkhirianov** [comment]
Делает Тихомиров Павел.

**Comment by tkhirianov** [comment]
Руслан Пашков вычитывает то, что исправляет Павел Тихомиров.

**Comment by Snorch** [comment]
http://judge.mipt.ru/mipt_cs_on_python3/drafts/lab8.html#id8 не получилось пофиксить форматирование(if/try), не пойму как это сделать в таблице. В онлайн редакторе http://rst.ninjs.org/?n=973e01f93f533966476d5d5f9807d5e7&theme=basic отображается с отступами.

Не получилось сделать нормальные ссылки, если уже есть input.txt то вторую ссылку с таким же именем сделать не получается, назвал input-5.txt, это возможно будет неинтуитивно для студентов.

В 6-й дал ссылки на словари из №5, наверное надо еще там рандомные строчки повыкидывать перед тем как тестить.

Добавил №8 - получился такой скрытый поиск в графе.

**Comment by tkhirianov** [comment]
Алексей, ты лучше всех разбираешься в rst формате. Помоги сделать отступы для исходного кода в таблице. Ну и разрывы строк чтобы не так страшно выглядели.
