### ISSUE TITLE
Контрольная билет 17

### ISSUE THREAD

**Issue by RerRayne** [mipt-cs-on-python3/course-site#26]
Слишком халявен, оба вопроса, фактически, про одно и тоже.

**Comment by tkhirianov** [comment]
Поскольку билеты генерируются случайным образом каждый раз, такое возможно.
`
questions1 = syntax*3
questions2 = theor_algo*3
assert len(questions1) == len(questions2)

for n, q1, q2 in zip(range(1, len(questions1)+1), questions1, questions2):
    print('Билет №', n)
    print('1.', q1)
    print('2.', q2)
    print()
    print()
`

Я должен был высмотреть это и перезапустить генерацию. Но в таком виде билеты всё равно больше не будут использованы никогда.
