### ISSUE TITLE
Лабораторная №10 "Объектно-ориентированное программирование" - доработка

### ISSUE THREAD

**Issue by tkhirianov** [mipt-cs-on-python3/course-site#28]
Нужно вычитать, вычистить и сделать адекватной по объёму (чтобы успели за пару) [работу №11 прошлого года](http://judge.mipt.ru/mipt_cs_on_python3_2015/labs/lab11.html) (теперь она №10):

**Содержание старой работы:**
- Основные понятия
- Поля и методы
- Стандартные методы
- Переопределение стандартных операций
- Функции type и isinstance
- Упражнения

**Я предлагаю сделать так:**

1 часть работы:
1. Основные понятия ООП.
2. Поля и методы. Стандартные методы.
3. **Доработка игры «Пушка».**  --- _ЭТО УПРАЖНЕНИЕ №6 в старой работе_

2 часть работы:
1. Переопределение стандартных операций.  --- _только после того, как они почувствуют вкус ООП, давать эти мелочи_
2. Функции type и isinstance.
3. Создание класса Vector. --- _для тех, кто доберётся_

**Comment by yudai-patronai** [comment]
а зачем чтоб за пару успели? почему не за 2?

28 октября 2016 г., 20:09 пользователь Timofey Khirianov <
notifications@github.com> написал:

**Comment by senya** [comment]
Иногда говорят, что объекты посылают друг другу сообщения. Сообщения -это запросы к объекту выполнить некоторые действия. (Сообщения, методы, операции, функции-члены являются синонимами).
 - что-то никогда не слышал чтоб методы называли сообщениями. да и операции - слишком общее слово

**Comment by senya** [comment]
lab rework merged.
Таску закрываю. Лабу значительно переписал, может не выполнил всех требований таски, будут пожелания - открывайте новый баг. Впрочем, по итогам совещния, ООП в первом семестре вообще оказалось под сомнением.
