### ISSUE TITLE
Контест 8, задача С рыцари и лжецы

### ISSUE THREAD

**Issue by RerRayne** [mipt-cs-on-python3/course-site#29]
В условии не хватает упоминания о том, что система может быть не десятичной.

**Comment by tkhirianov** [comment]
Приоритет ниже, чем создание д.з. к лекциям 9-11

**Comment by yudai-patronai** [comment]
В рыцарях и лжецах - какая ж система исчисления???

2016-11-28 13:15 GMT+04:00 Timofey Khirianov <notifications@github.com>:

**Comment by tkhirianov** [comment]
@RerRayne , ответь Мише и переоткрой багу, если он тебя не так понял.

**Comment by yudai-patronai** [comment]
А лучше напиши прям в телеграм прям мне. Вообще по всем воппосам о
контестах лучше мне в телеграм. На почте я уже перестаю успевать спам
просеивать.

30 Ноя 2016 г. 17:38 пользователь "Timofey Khirianov" <
notifications@github.com> написал:
