### ISSUE TITLE
Уточнение контеста

### ISSUE THREAD

**Issue by FeldmarshalAlex** [mipt-cs-on-python3/course-site#33]
Контест: перевод графа из одной формы в другую, поиск в ширину и глубину, поиск кратчайшего пути.
Ответственный: Маркеева
Критик: Хайруллин

Задача: сформировать требования к контесту.

**Comment by tkhirianov** [comment]
Есть три подходящих задачи в контесте: http://judge2.vdi.mipt.ru/cgi-bin/new-client?contest_id=540203

- Задача C-Связный ли граф?
- Задача D-Количество компонент связности
- Задача E-Сильно связный ли орграф?

Первые две оттуда брать нельзя - они войдут в домашний контест ко 2-й лекции.

Нужно **сделать** задачи:

- A. Списки смежности в список рёбер
- B. Список взвешенных рёбер в словарь словарей смежности
- F. Количество сильно связных и слабо связных компонент орграфа.
- G. Вывести остовное дерево графа, если граф связный и NO, если не связный.
- H. Проверить, что орграф - ациклический
- I. Найти диаметр графа (при помощи двух поисков в глубину)
- J. Проверить, Эйлеров ли граф.

**Comment by tkhirianov** [comment]
Как выкладываем промежуточный результат:
заливаете 

1. условие задачи, 
2. образцовое решение 
3. генератор тестов ( или сами тесты )
4. чекер
5. короткое описание каждой задачи в текстовичке Markdown, содержащее кусочек конфига для этой задачи 

в папку **2_03_lab**
в репозиторий: https://github.com/mipt-cs-on-python3/contests/tree/master/2016-2017_python3

Образец условий, генераторов, чекера и описания скоро скину.

**Comment by tkhirianov** [comment]
Думаю, можно заводить только одну issue, которую назначать сразу на ответственного и "критика".
