### ISSUE TITLE
Контест 4

### ISSUE THREAD

**Issue by FeldmarshalAlex** [mipt-cs-on-python3/course-site#34]
Контест: поиск в ширину, поиск кратчайшего пути.
Ответственный: Семенцов-Огиевский
Критик: Хламов

Дедлайн передачи критику: 20:00 22 февраля
Дедлайн передачи в общий доступ: 20:00 24 февраля

**Comment by tkhirianov** [comment]
Нужно сделать задачи:
- [ ] Осуществить обход в ширину и вывести количество рёбер на пути к каждой вершине из исходной. 
- [ ] Построить остовное дерево обходом в ширину.
- [ ] Поиск кратчайшего пути между двумя узлами невзвешенного графа
- [ ] Волновой алгоритм поиска пути в плоском лабиринте со стенами.
- [ ] Нахождение кратчайшего цикла в ориентированном невзвешенном графе [ссылка](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%B8%D1%81%D0%BA_%D0%B2_%D1%88%D0%B8%D1%80%D0%B8%D0%BD%D1%83#cite_note-emaxx-1)

Ещё пять задач не придумал.

**Comment by tkhirianov** [comment]
- [ ] Кузнечик-брокер. Восстановление оптимального пути для кузнечика-брокера.
- [ ] Поиск **длины** кратчайшего пути при помощи алгоритма Дейкстры. (без восстановления пути)
- [ ] Восстановление кратчайшего пути при помощи алгоритма Дейкстры.
- [ ] Нахождение вершины-"столицы", от которой сумма кратчайших расстояний до каждой вершины минимальна.

**Comment by senya** [comment]
Так, начну первые три делать.

**Comment by senya** [comment]
Залил первую.

**Comment by tkhirianov** [comment]
Владимир, остовное дерево обходом в ширину уже существует. Его нужно только отформатировать для нашего задачника и залить. Это "Дерево поиска в ширину" на странице https://server.179.ru/tasks/python/2017b1/pgm33__Graphs-2.html
Тесты, чекер и т.д. лежат тут: https://github.com/mipt-cs-on-python3/contests/tree/master/contests_from_dkirienko/000512/problems/21

**Comment by senya** [comment]
умереть и не встать, одна задача осталась

**Comment by senya** [comment]
такс, ну вот все есть. По хорошему конечно надо еще тестов.. В волновом - нужно их просто понадобавлять вручную в test_generator.py. В остальных - неплохо бы подумать о каких-нибудь крайних случаях.

**Comment by senya** [comment]
по объему работы - неделя до дедлайна тому кто делает - это минимум критический. по хорошему конечно надо две.

**Comment by tkhirianov** [comment]
Максим (@mkhlamov), нужно очень быстро прорешать контест, чтобы сегодня мы уже всё утрясли.
Я его ещё не залил на Ejudge, пока решай глядя на условия задач.

**Comment by senya** [comment]
Закрываю. Хотя надеюсь найти время на доработку наработки ;)
