### ISSUE TITLE
Контест 3

### ISSUE THREAD

**Issue by FeldmarshalAlex** [mipt-cs-on-python3/course-site#35]
Контест: перевод графа из одной формы в другую, поиск в ширину и глубину, поиск кратчайшего пути.
Ответственный: Маркеева
Критик: Хайруллин

**Задание:** 
Есть три подходящих задачи в контесте: http://judge2.vdi.mipt.ru/cgi-bin/new-client?contest_id=540203

- [x] Задача C-Связный ли граф?
- [x] Задача D-Количество компонент связности
- [x] Задача E-Сильно связный ли орграф?

Первые две оттуда брать нельзя - они войдут в домашний контест ко 2-й лекции.

Нужно сделать задачи:

- [x] A. Списки смежности в список рёбер
- [x] B. Список взвешенных рёбер в словарь словарей смежности
- [x] F. Количество сильно связных и слабо связных компонент орграфа.
- [ ] G. Вывести остовное дерево графа, если граф связный и NO, если не связный.
- [ ] H. Проверить, что орграф - ациклический
- [ ] I. Найти диаметр графа (при помощи двух поисков в глубину)
- [x] J. Проверить, Эйлеров ли граф.

Как выкладываем промежуточный результат:
заливаете

    условие задачи,
    образцовое решение
    генератор тестов ( или сами тесты )
    чекер
    короткое описание каждой задачи в текстовичке Markdown, содержащее кусочек конфига для этой задачи

в папку 2_03_lab
в репозиторий: https://github.com/mipt-cs-on-python3/contests/tree/master/2016-2017_python3

Вот здесь можно посмотреть как я делаю генератор тестов:
https://github.com/mipt-cs-on-python3/contests/tree/master/2016-2017_python3/2_02_lab

В первой из задачек (A_dic1) можно посмотреть на нестандартный чекер — checker.py

Условия Ejudge принимает в xml виде. Пока я оставил statements как есть.
@fufler Хотелось бы придумать rst, который будет легко переводить в xml скриптом.

Дедлайн передачи критику : 20:00 19.02.17
Дедлайн согласований с критиком: 20:00 20.02.17

**Comment by tkhirianov** [comment]
Вот здесь можно посмотреть как я делаю генератор тестов:
https://github.com/mipt-cs-on-python3/contests/tree/master/2016-2017_python3/2_02_lab

В первой из задачек (A_dic1) можно посмотреть на нестандартный чекер — checker.py

Условия Ejudge принимает в xml виде. Пока я оставил statements как есть.
@fufler Хотелось бы придумать rst, который будет легко переводить в xml скриптом.

**Comment by fufler** [comment]
@tkhirianov Какой формат xml-я нужен ejudge?

**Comment by tkhirianov** [comment]
@fufler , вот такой:

```
<?xml version="1.0" encoding="utf-8" ?>
    <problem
       package = "ru.ejudge.sample_contest"
       id = "B"
       type = "standard">
      <statement language="ru_RU">
        <title> Слияние псевдо-отсортированных списков </title>
        <description>
            <p>Осуществить слияние merge(A, B) двух данных списков строго по правилам сортировки слиянием по возрастанию.</p>
	        <p>При этом сами списки возрастающими (неубывающими) не являются.</p>
	        <p></p>
        </description>
      </statement>
      <examples>
        <example>
          <input>1 3 5 7
2 4 6 8
</input>
          <output>1 2 3 4 5 6 7 8
</output>
        </example>
      <example>
      <input>1 3 7 2
8 4 9
</input>
      <output>1 3 7 2 8 4 9
</output>
    </example>
      </examples>
    </problem>
```

**Comment by tkhirianov** [comment]
Пример конфигов задач (для контеста 2-й лабы):
```
[problem]
id = 1
super = "Generic_xml"
short_name = "A_dict1"
long_name = "Использование словарей"
type = "standard"
full_score = 100
open_tests = "1-3:full"
check_cmd = "checker.py"

[problem]
id = 2
super = "Generic_xml"
short_name = "B_merge1"
long_name = "Слияние псевдо-отсортированных списков"
full_score = 100
open_tests = "1-3:full"
standard_checker = "cmp_long_long_seq"

[problem]
id = 3
super = "Generic_xml"
short_name = "C_dynprog1"
long_name = "Динамическое программирование"
full_score = 100
open_tests = "1-3:full"
standard_checker = "cmp_long_long"

[problem]
id = 6
super = "Generic_xml"
short_name = "H_advertisement"
long_name = "Рекламная акция"
full_score = 100
open_tests = "1-3:full"
standard_checker = "cmp_file"

[problem]
id = 7
super = "Generic_xml"
short_name = "M_2d_array"
long_name = "Одномерный список в двумерный"
full_score = 100
open_tests = "1-3:full"
standard_checker = "cmp_file"

[problem]
id = 8
super = "Generic_xml"
short_name = "N_2d_array_rotation"
long_name = "Поворот прямоугольного массива"
full_score = 100
open_tests = "1-3:full"
standard_checker = "cmp_file"

[problem]
id = 9
super = "Generic_xml"
short_name = "Y_kuznechiki"
long_name = "Кузнечики"
full_score = 100
open_tests = "1-3:full"
standard_checker = "cmp_int_seq"

[problem]
id = 10
super = "Generic_xml"
short_name = "Z_queen"
long_name = "Ферзи"
full_score = 100
open_tests = "1-3:full"
standard_checker = "cmp_yesno"
```

**Comment by vasyarv** [comment]
Беру пока:
A. Списки смежности в список рёбер
B. Список взвешенных рёбер в словарь словарей смежности
J. Проверить, Эйлеров ли граф.

**Comment by Mikari** [comment]
Сделал F:
https://github.com/mipt-cs-on-python3/problembook/tree/master/problems/graphs/connectivity/weak-and-strong-components

Не очень понял как правильно генерировать id :-)

Бонус: я запилил у себя два простеньких генератора случайных графов - может быть полезно для других задач.

**Comment by vasyarv** [comment]
Сделал А:
https://github.com/mipt-cs-on-python3/problembook/tree/master/problems/graphs/connectivity/adj-matrix-to-edges

Спасибо за генераторы графов :)

**Comment by tkhirianov** [comment]
Итого было сделано 6 задач,но вроде бы студентам хватило.
