### ISSUE TITLE
Практика 4 - ответы к заданиям!

### ISSUE THREAD

**Issue by tkhirianov** [mipt-cs-on-python3/course-site#4]
Нужно срочно выложить ответы к упражнениям сегодняшней работы!
Иначе мы потеряем интерес студентов. Пока ещё эта работа "на острие", нужно успеть выложить ответы, тогда они их просмотрят.

**Comment by tkhirianov** [comment]
Руслану

**Comment by rpashkoff** [comment]
Сегодня не успеваю, спать очень хочется. Завтра пришлю.

**Comment by fufler** [comment]
Ответы выложены. Закрываю.
