### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by ghost** [mipt-cs-on-python3/course-site#9]
Доброго времени суток!

Заметил парочку опечаток в уроке №2 ("Введение в Python 3"):

1) В главе "IPython — расширенная оболочка": в коде строка "ABC" умножается на 10, а в поясняющем тексте ниже сказано, что строка умножается на 100;

2) В упражнении №8 в условии перепутаны ввод и вывод.

В дальнейшем предлагаю собирать всю информацию об опечатках здесь.
![dhdetmucyxg](https://cloud.githubusercontent.com/assets/7492555/10797098/7833b71e-7dba-11e5-8f14-ef425bf2abe3.jpg)
![tcjyp-3vyhy](https://cloud.githubusercontent.com/assets/7492555/10797108/84cc58aa-7dba-11e5-8735-4ed3df61f2f5.jpg)

**Comment by fufler** [comment]
[Исправил](https://github.com/mipt-cs-on-python3/course-site/commit/94c65f5fa5792d16d7e19f672f46c3065985faa9).

**Comment by tkhirianov** [comment]
@fufler , надо было сразу закрыть issue.
